### ISSUE TITLE
I2C has new wrappers in 4.4

### ISSUE THREAD

**Issue by davidhbrown-uri** [davidhbrown-uri/laser_scarecrow-ls22_esp32#7]
[ESP-IDF Release v4.4 notes](https://github.com/espressif/esp-idf/releases) mention: 

> I2C: Added wrappers for simplifying writes, reads and write-reads

The test branch was developed with ESP-IDF 4.3, so these wrappers were not available. Might want to update the test code? Haven't looked at the documentation yet. Maybe if we implement a "bubble level" mode with the accelerometer ever.

**Comment by davidhbrown** [comment]
Never mind. Any refactoring like that should focus on ESP-IDF 5.x
